---
kind: pipeline
type: docker
name: development

workspace:
  base: /go/src/coding.pickflames.com/pickflames
  path: monitor

steps:
- name: build
  image: golang:1.16-buster
  environment:
    CGO_ENABLED: 0
    GOOS: linux
    GOARCH: amd64
    GO111MODULE: on
    GOPROXY: https://goproxy.cn
  commands:
  - go version
  - cd  ../
  - git clone https://coding.pickflames.com/pickflames/framework.git
  - cd -
  - go vet ./...
  - |
    if test "${DRONE_TAG}" = ""; then
       go build -v -ldflags "-X main.build=${DRONE_COMMIT_SHA:0:8}" -a -o build/monitor
    else
       go build -v -ldflags "-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_COMMIT_SHA:0:8}" -a -o build/monitor
    fi

- name: docker
  image: plugins/docker
  repo: registry.pickflames.com/monitor
  registry: registry.pickflames.com
  context: build
  dockerfile: build/Dockerfile
  auto_tag: true
  secrets: [ docker_username, docker_password ]

- name: notify-failure
  image: plugins/webhook
  secrets:
    - source: dingtalk_url
      target: webhook_urls
  when:
    status: [ failure ]
  template: |
    {
      "msgtype": "text",
      "text": {
        "content": "{{ repo.name }} build {{ build.status }}"
      }
    }
