---
kind: pipeline
type: docker
name: default

workspace:
  base: /go/src/coding.pickflames.com/pickflames
  path: monitor

steps:
- name: build
  image: golang:1.18-buster
  environment:
    CGO_ENABLED: 0
    GOOS: linux
    GOARCH: amd64
    GO111MODULE: on
    GOPROXY: https://goproxy.cn
    GOPRIVATE: coding.pickflames.com
    GONOPROXY: coding.pickflames.com
    GONOSUMDB: coding.pickflames.com
  commands:
  - go version
  - go vet ./...
  - |
    if test "${DRONE_TAG}" = ""; then
       go build -v -ldflags "-X main.build=${DRONE_COMMIT_SHA:0:8}" -a -o build/monitor
    else
       go build -v -ldflags "-X main.version=${DRONE_TAG##v} -X main.build=${DRONE_COMMIT_SHA:0:8}" -a -o build/monitor
    fi

- name: docker
  image: plugins/docker
  settings:
    repo: registry.pickflames.com/monitor
    registry: registry.pickflames.com
    context: build
    dockerfile: build/Dockerfile
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: notify-failure
  image: plugins/webhook
  when:
    status: [ failure ]
  settings:
    urls:
      from_secret: dingtalk_url
    template: |
      {
        "msgtype": "text",
        "text": {
          "content": "{{ repo.name }} build {{ build.status }}"
        }
      }
